### ISSUE TITLE
Sugarizer 1.3.0 failed to install on Ubuntu 20.04 LTS on Raspberry Pi

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2360]
@llaske this is just an FYI as re-running it a 2nd time worked.

Likely the failure was due to a brief DNS failure while running npm below &mdash; here's the former error on Ubuntu 20.04's final release with Node.js 12.16.2 and npm 6.14.4:

> 2020-04-24 04:13:55,398 p=95290 u=root n=ansible | TASK [sugarizer : For http://box/sugarizer -- run 'npm install --allow-root --unsafe-perm=true path-prefix-proxy' to create /opt/iiab/sugarizer-server/node_modules/path-prefix-proxy] *********************************************************
2020-04-24 04:14:03,138 p=95290 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["npm", "install", "--allow-root", "--unsafe-perm=true", "path-prefix-proxy"], "delta": "0:00:07.035498", "end": "2020-04-24 04:14:03.033499", "msg": "non-zero return code", "rc": 1, "start": "2020-04-24 04:13:55.998001", "stderr": "npm ERR! code EAI_AGAIN\nnpm ERR! errno EAI_AGAIN\nnpm ERR! request to https://registry.npmjs.org/path-prefix-proxy failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2020-04-24T04_14_02_969Z-debug.log", "stderr_lines": ["npm ERR! code EAI_AGAIN", "npm ERR! errno EAI_AGAIN", "npm ERR! request to https://registry.npmjs.org/path-prefix-proxy failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /root/.npm/_logs/2020-04-24T04_14_02_969Z-debug.log"], "stdout": "", "stdout_lines": []}

And further detail...

> root@ubuntu:~# more /root/.npm/_logs/2020-04-24T04_14_02_969Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--allow-root',
1 verbose cli   '--unsafe-perm=true',
1 verbose cli   'path-prefix-proxy'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session 8894fe2f3d65d687
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for path-prefix-proxy@latest request to https
://registry.npmjs.org/path-prefix-proxy failed, reason: getaddrinfo EAI_AGAIN re
gistry.npmjs.org
8 timing stage:rollbackFailedOptional Completed in 3ms
9 timing stage:runTopLevelLifecycles Completed in 5048ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npmjs.org/path-prefix-p
roxy failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
11 verbose stack     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/nod
e_modules/node-fetch-npm/src/index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:310:20)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:426:9)
11 verbose stack     at TLSSocket.emit (events.js:310:20)
11 verbose stack     at emitErrorNT (internal/streams/destroy.js:92:8)
11 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.
js:84:21)
12 verbose cwd /opt/iiab/sugarizer-server-1.2.0
13 verbose Linux 5.4.0-1008-raspi
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--allow-root" "--unsaf
e-perm=true" "path-prefix-proxy"
15 verbose node v12.16.2
16 verbose npm  v6.14.4
17 error code EAI_AGAIN
18 error errno EAI_AGAIN
19 error request to https://registry.npmjs.org/path-prefix-proxy failed, reason:
 getaddrinfo EAI_AGAIN registry.npmjs.org
20 verbose exit [ 1, true ]

**Comment by llaske** [comment]
Thanks for notification.
I've upgraded my laptop to Ubuntu 20.04 LTS and both Sugarizer and Sugarizer Server seems to work.
